#print("안녕하세요." + "반갑습니다.")
#print("안녕하세요" * 5)
# print("안녕하세요"+10) Error 문자열 + 숫자시 에러 발생
#print("hello"[0])
#print("hello"[1])
#print("hello"[2])
#print("hello"[3])
#print("hello"[4])
#print("hello"[-1])
#print("hello"[1:3])
#print("hello"[2:4])
#print("hello"[:3])
#print("hello"[2:])
#print("hello"[1:99])
#pint("hello"[100]) # Error out of index
print(len("hello"))